// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectRootNamespace.Api.DataAccess;

namespace ProjectRootNamespace.Api.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20200628005002_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:postgis", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ProjectRootNamespace.Api.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'101', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #1",
                            Name = "Product #1",
                            Price = 52.260178781701335,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #2",
                            Name = "Product #2",
                            Price = 366.65403055802642,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #3",
                            Name = "Product #3",
                            Price = 366.64043816860789,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #4",
                            Name = "Product #4",
                            Price = 242.57839392059407,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #5",
                            Name = "Product #5",
                            Price = 104.91185397604102,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #6",
                            Name = "Product #6",
                            Price = 437.53304026906056,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #7",
                            Name = "Product #7",
                            Price = 127.13465692900803,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #8",
                            Name = "Product #8",
                            Price = 581.07150105762832,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #9",
                            Name = "Product #9",
                            Price = 107.33120677775294,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #10",
                            Name = "Product #10",
                            Price = 74.980149698900121,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #11",
                            Name = "Product #11",
                            Price = 340.35718049963805,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #12",
                            Name = "Product #12",
                            Price = 442.63617874245915,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #13",
                            Name = "Product #13",
                            Price = 315.36200660297737,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #14",
                            Name = "Product #14",
                            Price = 12.065702267021733,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #15",
                            Name = "Product #15",
                            Price = 189.84868898887592,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #16",
                            Name = "Product #16",
                            Price = 8.4488516554463899,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #17",
                            Name = "Product #17",
                            Price = 7.4212433450954229,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #18",
                            Name = "Product #18",
                            Price = 551.0116507816183,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #19",
                            Name = "Product #19",
                            Price = 241.45489282508143,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #20",
                            Name = "Product #20",
                            Price = 73.152853944875687,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #21",
                            Name = "Product #21",
                            Price = 82.119740531835575,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #22",
                            Name = "Product #22",
                            Price = 30.964904068487186,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #23",
                            Name = "Product #23",
                            Price = 426.58989766919512,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #24",
                            Name = "Product #24",
                            Price = 26.38267374429045,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #25",
                            Name = "Product #25",
                            Price = 69.907074054194183,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #26",
                            Name = "Product #26",
                            Price = 39.618601412334762,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #27",
                            Name = "Product #27",
                            Price = 417.99173386860252,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #28",
                            Name = "Product #28",
                            Price = 662.36586472409124,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #29",
                            Name = "Product #29",
                            Price = 2.7212577065086263,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #30",
                            Name = "Product #30",
                            Price = 54.759144207350516,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #31",
                            Name = "Product #31",
                            Price = 105.71184289348862,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #32",
                            Name = "Product #32",
                            Price = 277.18264882135327,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #33",
                            Name = "Product #33",
                            Price = 231.77403937269656,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #34",
                            Name = "Product #34",
                            Price = 583.55912169840144,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #35",
                            Name = "Product #35",
                            Price = 25.592236476294808,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #36",
                            Name = "Product #36",
                            Price = 215.25985731988209,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #37",
                            Name = "Product #37",
                            Price = 160.86357049730773,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #38",
                            Name = "Product #38",
                            Price = 98.721300608814374,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #39",
                            Name = "Product #39",
                            Price = 153.25932911795533,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #40",
                            Name = "Product #40",
                            Price = 233.05958755829352,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #41",
                            Name = "Product #41",
                            Price = 7.0547414166176425,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #42",
                            Name = "Product #42",
                            Price = 527.78464479827539,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #43",
                            Name = "Product #43",
                            Price = 296.50324009941107,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #44",
                            Name = "Product #44",
                            Price = 382.26134290092688,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #45",
                            Name = "Product #45",
                            Price = 79.140032678442097,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #46",
                            Name = "Product #46",
                            Price = 184.15474657581873,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #47",
                            Name = "Product #47",
                            Price = 250.00597851584013,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #48",
                            Name = "Product #48",
                            Price = 557.57392709030489,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #49",
                            Name = "Product #49",
                            Price = 645.2805915499481,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #50",
                            Name = "Product #50",
                            Price = 19.755481030212476,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #51",
                            Name = "Product #51",
                            Price = 660.82413764336331,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #52",
                            Name = "Product #52",
                            Price = 217.09630021876484,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #53",
                            Name = "Product #53",
                            Price = 715.15179954336577,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #54",
                            Name = "Product #54",
                            Price = 12.108975342991284,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #55",
                            Name = "Product #55",
                            Price = 181.27364554036112,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #56",
                            Name = "Product #56",
                            Price = 30.022567937626764,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #57",
                            Name = "Product #57",
                            Price = 244.20309430183988,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #58",
                            Name = "Product #58",
                            Price = 11.113275320321915,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #59",
                            Name = "Product #59",
                            Price = 4.2750797468587196,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #60",
                            Name = "Product #60",
                            Price = 494.4064075217612,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #61",
                            Name = "Product #61",
                            Price = 609.71257755240072,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #62",
                            Name = "Product #62",
                            Price = 464.624694536731,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #63",
                            Name = "Product #63",
                            Price = 186.02751743794769,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #64",
                            Name = "Product #64",
                            Price = 5.2633875465315709,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #65",
                            Name = "Product #65",
                            Price = 177.4676310566569,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #66",
                            Name = "Product #66",
                            Price = 362.41341957562298,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #67",
                            Name = "Product #67",
                            Price = 557.39487191168348,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #68",
                            Name = "Product #68",
                            Price = 63.972743727254098,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #69",
                            Name = "Product #69",
                            Price = 23.392898764178575,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #70",
                            Name = "Product #70",
                            Price = 55.594217924212209,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #71",
                            Name = "Product #71",
                            Price = 297.85257233905259,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #72",
                            Name = "Product #72",
                            Price = 68.280275354292371,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #73",
                            Name = "Product #73",
                            Price = 251.36914875189271,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #74",
                            Name = "Product #74",
                            Price = 178.1001944179182,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #75",
                            Name = "Product #75",
                            Price = 156.11078624898138,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #76",
                            Name = "Product #76",
                            Price = 206.55610127679822,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #77",
                            Name = "Product #77",
                            Price = 280.11088218451982,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #78",
                            Name = "Product #78",
                            Price = 495.14041323407565,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #79",
                            Name = "Product #79",
                            Price = 238.59146274001873,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #80",
                            Name = "Product #80",
                            Price = 71.465091099713504,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 81,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #81",
                            Name = "Product #81",
                            Price = 123.73384353086996,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 82,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #82",
                            Name = "Product #82",
                            Price = 26.010980085474895,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 83,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #83",
                            Name = "Product #83",
                            Price = 119.02947764798508,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 84,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #84",
                            Name = "Product #84",
                            Price = 124.08046227883568,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 85,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #85",
                            Name = "Product #85",
                            Price = 105.88399931131117,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 86,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #86",
                            Name = "Product #86",
                            Price = 293.42840813259983,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 87,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #87",
                            Name = "Product #87",
                            Price = 576.49527616542548,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 88,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #88",
                            Name = "Product #88",
                            Price = 110.71632107520304,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 89,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #89",
                            Name = "Product #89",
                            Price = 92.797564564644162,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 90,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #90",
                            Name = "Product #90",
                            Price = 422.23627537267106,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 91,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #91",
                            Name = "Product #91",
                            Price = 21.731507765935508,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 92,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #92",
                            Name = "Product #92",
                            Price = 45.894778886760946,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 93,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #93",
                            Name = "Product #93",
                            Price = 69.719333040397302,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 94,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #94",
                            Name = "Product #94",
                            Price = 459.48041990188904,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 95,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #95",
                            Name = "Product #95",
                            Price = 597.93684613375774,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 96,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #96",
                            Name = "Product #96",
                            Price = 171.57096640512856,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 97,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #97",
                            Name = "Product #97",
                            Price = 56.859291980443196,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 98,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #98",
                            Name = "Product #98",
                            Price = 260.16160685576574,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 99,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #99",
                            Name = "Product #99",
                            Price = 564.88380528841344,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 100,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #100",
                            Name = "Product #100",
                            Price = 683.60557012753827,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
