// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectRootNamespace.Api.DataAccess;

namespace ProjectRootNamespace.Api.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20200628001452_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:postgis", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ProjectRootNamespace.Api.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'101', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #1",
                            Name = "Product #1",
                            Price = 36.985656091471043,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #2",
                            Name = "Product #2",
                            Price = 851.32247519740952,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #3",
                            Name = "Product #3",
                            Price = 154.8568547260281,
                            Stock = 3,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #4",
                            Name = "Product #4",
                            Price = 31.51580519299759,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #5",
                            Name = "Product #5",
                            Price = 0.85180458373008505,
                            Stock = 7,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #6",
                            Name = "Product #6",
                            Price = 4.6883207767681778,
                            Stock = 9,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #7",
                            Name = "Product #7",
                            Price = 5.348051466675499,
                            Stock = 7,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #8",
                            Name = "Product #8",
                            Price = 155.62790826877017,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #9",
                            Name = "Product #9",
                            Price = 432.86544877331028,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #10",
                            Name = "Product #10",
                            Price = 94.475551779603364,
                            Stock = 7,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #11",
                            Name = "Product #11",
                            Price = 76.30138369570551,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #12",
                            Name = "Product #12",
                            Price = 589.9082399718036,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #13",
                            Name = "Product #13",
                            Price = 200.60565771749506,
                            Stock = 8,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #14",
                            Name = "Product #14",
                            Price = 207.34922189421448,
                            Stock = 9,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #15",
                            Name = "Product #15",
                            Price = 138.54025251164111,
                            Stock = 2,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #16",
                            Name = "Product #16",
                            Price = 52.195072293838052,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #17",
                            Name = "Product #17",
                            Price = 342.91045746901563,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #18",
                            Name = "Product #18",
                            Price = 124.94723547852935,
                            Stock = 5,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #19",
                            Name = "Product #19",
                            Price = 223.00626515923358,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #20",
                            Name = "Product #20",
                            Price = 2.5046700008700928,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #21",
                            Name = "Product #21",
                            Price = 450.4549298949795,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #22",
                            Name = "Product #22",
                            Price = 93.435096130908988,
                            Stock = 8,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #23",
                            Name = "Product #23",
                            Price = 380.04858676439551,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #24",
                            Name = "Product #24",
                            Price = 308.81146111703083,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #25",
                            Name = "Product #25",
                            Price = 59.719521465115029,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #26",
                            Name = "Product #26",
                            Price = 601.77559539292736,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #27",
                            Name = "Product #27",
                            Price = 146.58037557060848,
                            Stock = 7,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #28",
                            Name = "Product #28",
                            Price = 29.705942834590534,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #29",
                            Name = "Product #29",
                            Price = 303.67425814814595,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #30",
                            Name = "Product #30",
                            Price = 446.77273121698425,
                            Stock = 7,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #31",
                            Name = "Product #31",
                            Price = 74.640651651956446,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #32",
                            Name = "Product #32",
                            Price = 688.20696517229408,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #33",
                            Name = "Product #33",
                            Price = 387.87485957232997,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #34",
                            Name = "Product #34",
                            Price = 341.71458506850274,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #35",
                            Name = "Product #35",
                            Price = 194.45858075956747,
                            Stock = 8,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #36",
                            Name = "Product #36",
                            Price = 361.9328800295167,
                            Stock = 9,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #37",
                            Name = "Product #37",
                            Price = 75.484058437628704,
                            Stock = 5,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #38",
                            Name = "Product #38",
                            Price = 494.41971102003924,
                            Stock = 7,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #39",
                            Name = "Product #39",
                            Price = 134.74828233884102,
                            Stock = 5,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #40",
                            Name = "Product #40",
                            Price = 108.90157009889444,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #41",
                            Name = "Product #41",
                            Price = 225.13416969828967,
                            Stock = 7,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #42",
                            Name = "Product #42",
                            Price = 46.569919555713383,
                            Stock = 5,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #43",
                            Name = "Product #43",
                            Price = 448.27365553857464,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #44",
                            Name = "Product #44",
                            Price = 205.21298673432926,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #45",
                            Name = "Product #45",
                            Price = 700.59562882343107,
                            Stock = 8,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #46",
                            Name = "Product #46",
                            Price = 32.834978116133705,
                            Stock = 9,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #47",
                            Name = "Product #47",
                            Price = 317.68407507132929,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #48",
                            Name = "Product #48",
                            Price = 100.24006114725026,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #49",
                            Name = "Product #49",
                            Price = 167.2211015444347,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #50",
                            Name = "Product #50",
                            Price = 282.62153022253028,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #51",
                            Name = "Product #51",
                            Price = 109.16345235107626,
                            Stock = 5,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #52",
                            Name = "Product #52",
                            Price = 85.886621727555351,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #53",
                            Name = "Product #53",
                            Price = 306.9458003765651,
                            Stock = 2,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #54",
                            Name = "Product #54",
                            Price = 16.282590713483557,
                            Stock = 8,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #55",
                            Name = "Product #55",
                            Price = 486.60821787575645,
                            Stock = 8,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #56",
                            Name = "Product #56",
                            Price = 308.44092162253378,
                            Stock = 9,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #57",
                            Name = "Product #57",
                            Price = 183.98418210632363,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #58",
                            Name = "Product #58",
                            Price = 9.4782721761047242,
                            Stock = 7,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #59",
                            Name = "Product #59",
                            Price = 28.329693688233242,
                            Stock = 5,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #60",
                            Name = "Product #60",
                            Price = 48.709492952893257,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #61",
                            Name = "Product #61",
                            Price = 22.779631870230489,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #62",
                            Name = "Product #62",
                            Price = 647.98284162440473,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #63",
                            Name = "Product #63",
                            Price = 430.50256567332087,
                            Stock = 2,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #64",
                            Name = "Product #64",
                            Price = 44.525887508190188,
                            Stock = 9,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #65",
                            Name = "Product #65",
                            Price = 405.21200553197974,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #66",
                            Name = "Product #66",
                            Price = 276.55602869417334,
                            Stock = 9,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #67",
                            Name = "Product #67",
                            Price = 593.36050256032524,
                            Stock = 9,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #68",
                            Name = "Product #68",
                            Price = 394.12613953190208,
                            Stock = 2,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #69",
                            Name = "Product #69",
                            Price = 231.07280849063432,
                            Stock = 8,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #70",
                            Name = "Product #70",
                            Price = 76.306234678396137,
                            Stock = 9,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #71",
                            Name = "Product #71",
                            Price = 98.303680343694836,
                            Stock = 9,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #72",
                            Name = "Product #72",
                            Price = 87.606644512902321,
                            Stock = 8,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #73",
                            Name = "Product #73",
                            Price = 615.51964873006557,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #74",
                            Name = "Product #74",
                            Price = 404.34821957971349,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #75",
                            Name = "Product #75",
                            Price = 447.03978526361277,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #76",
                            Name = "Product #76",
                            Price = 90.731710603801403,
                            Stock = 5,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #77",
                            Name = "Product #77",
                            Price = 202.88293228618937,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #78",
                            Name = "Product #78",
                            Price = 194.17291770790374,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #79",
                            Name = "Product #79",
                            Price = 283.63224708877141,
                            Stock = 3,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #80",
                            Name = "Product #80",
                            Price = 296.30411063707623,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 81,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #81",
                            Name = "Product #81",
                            Price = 466.87778152612867,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 82,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #82",
                            Name = "Product #82",
                            Price = 38.217318122376369,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 83,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #83",
                            Name = "Product #83",
                            Price = 0.93091542317108966,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 84,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #84",
                            Name = "Product #84",
                            Price = 337.29492045626739,
                            Stock = 7,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 85,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #85",
                            Name = "Product #85",
                            Price = 214.77075264918187,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 86,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #86",
                            Name = "Product #86",
                            Price = 593.30496047311692,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 87,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #87",
                            Name = "Product #87",
                            Price = 36.813036111562063,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 88,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #88",
                            Name = "Product #88",
                            Price = 129.80728208916599,
                            Stock = 6,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 89,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #89",
                            Name = "Product #89",
                            Price = 534.05982207230284,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 90,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #90",
                            Name = "Product #90",
                            Price = 116.27146381245529,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 91,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #91",
                            Name = "Product #91",
                            Price = 504.51121649914944,
                            Stock = 5,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 92,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #92",
                            Name = "Product #92",
                            Price = 627.98725065122699,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 93,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #93",
                            Name = "Product #93",
                            Price = 218.90468777106364,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 94,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #94",
                            Name = "Product #94",
                            Price = 20.863248947944143,
                            Stock = 8,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 95,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #95",
                            Name = "Product #95",
                            Price = 73.642321442087336,
                            Stock = 8,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 96,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #96",
                            Name = "Product #96",
                            Price = 186.85227870561755,
                            Stock = 2,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 97,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #97",
                            Name = "Product #97",
                            Price = 277.24270158877721,
                            Stock = 1,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 98,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #98",
                            Name = "Product #98",
                            Price = 783.66393151863667,
                            Stock = 9,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 99,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #99",
                            Name = "Product #99",
                            Price = 174.15821688489905,
                            Stock = 4,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 100,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #100",
                            Name = "Product #100",
                            Price = 28.656266870282714,
                            Stock = 5,
                            UpdatedBy = "system",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
