// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectName.Api.DataAccess;

namespace ProjectName.Api.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ProjectName.Api.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Deleted = false,
                            Description = "",
                            Name = "Product #1",
                            Price = 215.93966390329396,
                            Stock = 8
                        },
                        new
                        {
                            Id = -2,
                            Deleted = false,
                            Description = "",
                            Name = "Product #2",
                            Price = 164.68056481549542,
                            Stock = 5
                        },
                        new
                        {
                            Id = -3,
                            Deleted = false,
                            Description = "",
                            Name = "Product #3",
                            Price = 51.30898750541219,
                            Stock = 7
                        },
                        new
                        {
                            Id = -4,
                            Deleted = false,
                            Description = "",
                            Name = "Product #4",
                            Price = 51.789082955470818,
                            Stock = 5
                        },
                        new
                        {
                            Id = -5,
                            Deleted = false,
                            Description = "",
                            Name = "Product #5",
                            Price = 585.98804495809043,
                            Stock = 4
                        },
                        new
                        {
                            Id = -6,
                            Deleted = false,
                            Description = "",
                            Name = "Product #6",
                            Price = 203.33743729225239,
                            Stock = 7
                        },
                        new
                        {
                            Id = -7,
                            Deleted = false,
                            Description = "",
                            Name = "Product #7",
                            Price = 109.70660716141883,
                            Stock = 5
                        },
                        new
                        {
                            Id = -8,
                            Deleted = false,
                            Description = "",
                            Name = "Product #8",
                            Price = 3.7527416179667887,
                            Stock = 9
                        },
                        new
                        {
                            Id = -9,
                            Deleted = false,
                            Description = "",
                            Name = "Product #9",
                            Price = 661.20404083151561,
                            Stock = 8
                        },
                        new
                        {
                            Id = -10,
                            Deleted = false,
                            Description = "",
                            Name = "Product #10",
                            Price = 226.69940769146172,
                            Stock = 9
                        },
                        new
                        {
                            Id = -11,
                            Deleted = false,
                            Description = "",
                            Name = "Product #11",
                            Price = 214.24760202143696,
                            Stock = 3
                        },
                        new
                        {
                            Id = -12,
                            Deleted = false,
                            Description = "",
                            Name = "Product #12",
                            Price = 30.120070278700474,
                            Stock = 9
                        },
                        new
                        {
                            Id = -13,
                            Deleted = false,
                            Description = "",
                            Name = "Product #13",
                            Price = 795.4163215958589,
                            Stock = 7
                        },
                        new
                        {
                            Id = -14,
                            Deleted = false,
                            Description = "",
                            Name = "Product #14",
                            Price = 32.335398496284803,
                            Stock = 5
                        },
                        new
                        {
                            Id = -15,
                            Deleted = false,
                            Description = "",
                            Name = "Product #15",
                            Price = 7.6061924601002566,
                            Stock = 2
                        },
                        new
                        {
                            Id = -16,
                            Deleted = false,
                            Description = "",
                            Name = "Product #16",
                            Price = 32.35410206408897,
                            Stock = 7
                        },
                        new
                        {
                            Id = -17,
                            Deleted = false,
                            Description = "",
                            Name = "Product #17",
                            Price = 6.2728425293568719,
                            Stock = 3
                        },
                        new
                        {
                            Id = -18,
                            Deleted = false,
                            Description = "",
                            Name = "Product #18",
                            Price = 522.83045235408019,
                            Stock = 8
                        },
                        new
                        {
                            Id = -19,
                            Deleted = false,
                            Description = "",
                            Name = "Product #19",
                            Price = 501.61375575028995,
                            Stock = 2
                        },
                        new
                        {
                            Id = -20,
                            Deleted = false,
                            Description = "",
                            Name = "Product #20",
                            Price = 281.91596419686266,
                            Stock = 2
                        },
                        new
                        {
                            Id = -21,
                            Deleted = false,
                            Description = "",
                            Name = "Product #21",
                            Price = 345.45434685910789,
                            Stock = 8
                        },
                        new
                        {
                            Id = -22,
                            Deleted = false,
                            Description = "",
                            Name = "Product #22",
                            Price = 451.20038103461286,
                            Stock = 1
                        },
                        new
                        {
                            Id = -23,
                            Deleted = false,
                            Description = "",
                            Name = "Product #23",
                            Price = 170.50483840354943,
                            Stock = 2
                        },
                        new
                        {
                            Id = -24,
                            Deleted = false,
                            Description = "",
                            Name = "Product #24",
                            Price = 350.37042451015225,
                            Stock = 5
                        },
                        new
                        {
                            Id = -25,
                            Deleted = false,
                            Description = "",
                            Name = "Product #25",
                            Price = 73.028415103921859,
                            Stock = 1
                        },
                        new
                        {
                            Id = -26,
                            Deleted = false,
                            Description = "",
                            Name = "Product #26",
                            Price = 20.122413418778411,
                            Stock = 7
                        },
                        new
                        {
                            Id = -27,
                            Deleted = false,
                            Description = "",
                            Name = "Product #27",
                            Price = 207.4954969396328,
                            Stock = 7
                        },
                        new
                        {
                            Id = -28,
                            Deleted = false,
                            Description = "",
                            Name = "Product #28",
                            Price = 48.714803137683681,
                            Stock = 2
                        },
                        new
                        {
                            Id = -29,
                            Deleted = false,
                            Description = "",
                            Name = "Product #29",
                            Price = 476.4736253146425,
                            Stock = 7
                        },
                        new
                        {
                            Id = -30,
                            Deleted = false,
                            Description = "",
                            Name = "Product #30",
                            Price = 144.55851454919136,
                            Stock = 8
                        },
                        new
                        {
                            Id = -31,
                            Deleted = false,
                            Description = "",
                            Name = "Product #31",
                            Price = 15.433354601000136,
                            Stock = 6
                        },
                        new
                        {
                            Id = -32,
                            Deleted = false,
                            Description = "",
                            Name = "Product #32",
                            Price = 239.08226833636047,
                            Stock = 5
                        },
                        new
                        {
                            Id = -33,
                            Deleted = false,
                            Description = "",
                            Name = "Product #33",
                            Price = 142.44710012220179,
                            Stock = 8
                        },
                        new
                        {
                            Id = -34,
                            Deleted = false,
                            Description = "",
                            Name = "Product #34",
                            Price = 66.417288077258178,
                            Stock = 4
                        },
                        new
                        {
                            Id = -35,
                            Deleted = false,
                            Description = "",
                            Name = "Product #35",
                            Price = 326.57595184751597,
                            Stock = 4
                        },
                        new
                        {
                            Id = -36,
                            Deleted = false,
                            Description = "",
                            Name = "Product #36",
                            Price = 726.63799853606054,
                            Stock = 6
                        },
                        new
                        {
                            Id = -37,
                            Deleted = false,
                            Description = "",
                            Name = "Product #37",
                            Price = 621.42806778449005,
                            Stock = 7
                        },
                        new
                        {
                            Id = -38,
                            Deleted = false,
                            Description = "",
                            Name = "Product #38",
                            Price = 80.33589071935782,
                            Stock = 1
                        },
                        new
                        {
                            Id = -39,
                            Deleted = false,
                            Description = "",
                            Name = "Product #39",
                            Price = 245.49416911112803,
                            Stock = 7
                        },
                        new
                        {
                            Id = -40,
                            Deleted = false,
                            Description = "",
                            Name = "Product #40",
                            Price = 112.16473163672011,
                            Stock = 8
                        },
                        new
                        {
                            Id = -41,
                            Deleted = false,
                            Description = "",
                            Name = "Product #41",
                            Price = 227.86650538624568,
                            Stock = 4
                        },
                        new
                        {
                            Id = -42,
                            Deleted = false,
                            Description = "",
                            Name = "Product #42",
                            Price = 261.48105153882926,
                            Stock = 6
                        },
                        new
                        {
                            Id = -43,
                            Deleted = false,
                            Description = "",
                            Name = "Product #43",
                            Price = 263.49396209860868,
                            Stock = 7
                        },
                        new
                        {
                            Id = -44,
                            Deleted = false,
                            Description = "",
                            Name = "Product #44",
                            Price = 159.33157131417263,
                            Stock = 8
                        },
                        new
                        {
                            Id = -45,
                            Deleted = false,
                            Description = "",
                            Name = "Product #45",
                            Price = 442.60120265772622,
                            Stock = 9
                        },
                        new
                        {
                            Id = -46,
                            Deleted = false,
                            Description = "",
                            Name = "Product #46",
                            Price = 174.61910297843588,
                            Stock = 2
                        },
                        new
                        {
                            Id = -47,
                            Deleted = false,
                            Description = "",
                            Name = "Product #47",
                            Price = 673.13744740473919,
                            Stock = 8
                        },
                        new
                        {
                            Id = -48,
                            Deleted = false,
                            Description = "",
                            Name = "Product #48",
                            Price = 107.00087242154446,
                            Stock = 6
                        },
                        new
                        {
                            Id = -49,
                            Deleted = false,
                            Description = "",
                            Name = "Product #49",
                            Price = 40.776269016683223,
                            Stock = 8
                        },
                        new
                        {
                            Id = -50,
                            Deleted = false,
                            Description = "",
                            Name = "Product #50",
                            Price = 126.05140751136999,
                            Stock = 7
                        },
                        new
                        {
                            Id = -51,
                            Deleted = false,
                            Description = "",
                            Name = "Product #51",
                            Price = 724.02526687925001,
                            Stock = 1
                        },
                        new
                        {
                            Id = -52,
                            Deleted = false,
                            Description = "",
                            Name = "Product #52",
                            Price = 22.479106414354924,
                            Stock = 5
                        },
                        new
                        {
                            Id = -53,
                            Deleted = false,
                            Description = "",
                            Name = "Product #53",
                            Price = 7.708889704062087,
                            Stock = 8
                        },
                        new
                        {
                            Id = -54,
                            Deleted = false,
                            Description = "",
                            Name = "Product #54",
                            Price = 662.10350051061414,
                            Stock = 6
                        },
                        new
                        {
                            Id = -55,
                            Deleted = false,
                            Description = "",
                            Name = "Product #55",
                            Price = 246.02968955041362,
                            Stock = 5
                        },
                        new
                        {
                            Id = -56,
                            Deleted = false,
                            Description = "",
                            Name = "Product #56",
                            Price = 562.62804546702091,
                            Stock = 6
                        },
                        new
                        {
                            Id = -57,
                            Deleted = false,
                            Description = "",
                            Name = "Product #57",
                            Price = 5.4103662233847967,
                            Stock = 1
                        },
                        new
                        {
                            Id = -58,
                            Deleted = false,
                            Description = "",
                            Name = "Product #58",
                            Price = 479.15207074869051,
                            Stock = 4
                        },
                        new
                        {
                            Id = -59,
                            Deleted = false,
                            Description = "",
                            Name = "Product #59",
                            Price = 92.026941061963768,
                            Stock = 3
                        },
                        new
                        {
                            Id = -60,
                            Deleted = false,
                            Description = "",
                            Name = "Product #60",
                            Price = 88.497980426297516,
                            Stock = 6
                        },
                        new
                        {
                            Id = -61,
                            Deleted = false,
                            Description = "",
                            Name = "Product #61",
                            Price = 297.28224122677102,
                            Stock = 1
                        },
                        new
                        {
                            Id = -62,
                            Deleted = false,
                            Description = "",
                            Name = "Product #62",
                            Price = 760.3438510887064,
                            Stock = 3
                        },
                        new
                        {
                            Id = -63,
                            Deleted = false,
                            Description = "",
                            Name = "Product #63",
                            Price = 633.99844441981907,
                            Stock = 6
                        },
                        new
                        {
                            Id = -64,
                            Deleted = false,
                            Description = "",
                            Name = "Product #64",
                            Price = 137.23689522931207,
                            Stock = 3
                        },
                        new
                        {
                            Id = -65,
                            Deleted = false,
                            Description = "",
                            Name = "Product #65",
                            Price = 38.335537136688615,
                            Stock = 9
                        },
                        new
                        {
                            Id = -66,
                            Deleted = false,
                            Description = "",
                            Name = "Product #66",
                            Price = 87.826087929227427,
                            Stock = 3
                        },
                        new
                        {
                            Id = -67,
                            Deleted = false,
                            Description = "",
                            Name = "Product #67",
                            Price = 43.084442854432595,
                            Stock = 6
                        },
                        new
                        {
                            Id = -68,
                            Deleted = false,
                            Description = "",
                            Name = "Product #68",
                            Price = 100.02500687540741,
                            Stock = 2
                        },
                        new
                        {
                            Id = -69,
                            Deleted = false,
                            Description = "",
                            Name = "Product #69",
                            Price = 110.33887133949383,
                            Stock = 2
                        },
                        new
                        {
                            Id = -70,
                            Deleted = false,
                            Description = "",
                            Name = "Product #70",
                            Price = 52.717702135777898,
                            Stock = 8
                        },
                        new
                        {
                            Id = -71,
                            Deleted = false,
                            Description = "",
                            Name = "Product #71",
                            Price = 77.217189542584677,
                            Stock = 1
                        },
                        new
                        {
                            Id = -72,
                            Deleted = false,
                            Description = "",
                            Name = "Product #72",
                            Price = 159.071797985617,
                            Stock = 5
                        },
                        new
                        {
                            Id = -73,
                            Deleted = false,
                            Description = "",
                            Name = "Product #73",
                            Price = 494.87235224939531,
                            Stock = 5
                        },
                        new
                        {
                            Id = -74,
                            Deleted = false,
                            Description = "",
                            Name = "Product #74",
                            Price = 18.891989522097628,
                            Stock = 8
                        },
                        new
                        {
                            Id = -75,
                            Deleted = false,
                            Description = "",
                            Name = "Product #75",
                            Price = 34.11006590542852,
                            Stock = 8
                        },
                        new
                        {
                            Id = -76,
                            Deleted = false,
                            Description = "",
                            Name = "Product #76",
                            Price = 143.6104251461152,
                            Stock = 7
                        },
                        new
                        {
                            Id = -77,
                            Deleted = false,
                            Description = "",
                            Name = "Product #77",
                            Price = 306.73564825148117,
                            Stock = 7
                        },
                        new
                        {
                            Id = -78,
                            Deleted = false,
                            Description = "",
                            Name = "Product #78",
                            Price = 568.39458982292308,
                            Stock = 8
                        },
                        new
                        {
                            Id = -79,
                            Deleted = false,
                            Description = "",
                            Name = "Product #79",
                            Price = 31.537496778898639,
                            Stock = 9
                        },
                        new
                        {
                            Id = -80,
                            Deleted = false,
                            Description = "",
                            Name = "Product #80",
                            Price = 218.69187159402847,
                            Stock = 6
                        },
                        new
                        {
                            Id = -81,
                            Deleted = false,
                            Description = "",
                            Name = "Product #81",
                            Price = 9.7404334953708744,
                            Stock = 7
                        },
                        new
                        {
                            Id = -82,
                            Deleted = false,
                            Description = "",
                            Name = "Product #82",
                            Price = 144.12886181107206,
                            Stock = 1
                        },
                        new
                        {
                            Id = -83,
                            Deleted = false,
                            Description = "",
                            Name = "Product #83",
                            Price = 44.278787693138604,
                            Stock = 2
                        },
                        new
                        {
                            Id = -84,
                            Deleted = false,
                            Description = "",
                            Name = "Product #84",
                            Price = 266.00528048165387,
                            Stock = 4
                        },
                        new
                        {
                            Id = -85,
                            Deleted = false,
                            Description = "",
                            Name = "Product #85",
                            Price = 810.58676840625094,
                            Stock = 2
                        },
                        new
                        {
                            Id = -86,
                            Deleted = false,
                            Description = "",
                            Name = "Product #86",
                            Price = 122.12783722771697,
                            Stock = 8
                        },
                        new
                        {
                            Id = -87,
                            Deleted = false,
                            Description = "",
                            Name = "Product #87",
                            Price = 353.10276746987495,
                            Stock = 9
                        },
                        new
                        {
                            Id = -88,
                            Deleted = false,
                            Description = "",
                            Name = "Product #88",
                            Price = 99.974790231312994,
                            Stock = 4
                        },
                        new
                        {
                            Id = -89,
                            Deleted = false,
                            Description = "",
                            Name = "Product #89",
                            Price = 21.635369800792716,
                            Stock = 7
                        },
                        new
                        {
                            Id = -90,
                            Deleted = false,
                            Description = "",
                            Name = "Product #90",
                            Price = 34.800885179918673,
                            Stock = 4
                        },
                        new
                        {
                            Id = -91,
                            Deleted = false,
                            Description = "",
                            Name = "Product #91",
                            Price = 403.37909162201879,
                            Stock = 7
                        },
                        new
                        {
                            Id = -92,
                            Deleted = false,
                            Description = "",
                            Name = "Product #92",
                            Price = 6.6245321103485919,
                            Stock = 1
                        },
                        new
                        {
                            Id = -93,
                            Deleted = false,
                            Description = "",
                            Name = "Product #93",
                            Price = 13.355281910558826,
                            Stock = 4
                        },
                        new
                        {
                            Id = -94,
                            Deleted = false,
                            Description = "",
                            Name = "Product #94",
                            Price = 430.25998604449444,
                            Stock = 9
                        },
                        new
                        {
                            Id = -95,
                            Deleted = false,
                            Description = "",
                            Name = "Product #95",
                            Price = 48.65831371427435,
                            Stock = 9
                        },
                        new
                        {
                            Id = -96,
                            Deleted = false,
                            Description = "",
                            Name = "Product #96",
                            Price = 33.489185878303452,
                            Stock = 6
                        },
                        new
                        {
                            Id = -97,
                            Deleted = false,
                            Description = "",
                            Name = "Product #97",
                            Price = 177.73698264348181,
                            Stock = 4
                        },
                        new
                        {
                            Id = -98,
                            Deleted = false,
                            Description = "",
                            Name = "Product #98",
                            Price = 32.335787512518365,
                            Stock = 3
                        },
                        new
                        {
                            Id = -99,
                            Deleted = false,
                            Description = "",
                            Name = "Product #99",
                            Price = 499.71650944078181,
                            Stock = 8
                        },
                        new
                        {
                            Id = -100,
                            Deleted = false,
                            Description = "",
                            Name = "Product #100",
                            Price = 254.05734611957212,
                            Stock = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
