// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectRootNamespace.Api.DataAccess;

namespace ProjectRootNamespace.Api.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:postgis", ",,")
                .HasAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ProjectRootNamespace.Api.DataAccess.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'101', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(64)")
                        .HasMaxLength(64);

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #1",
                            Name = "Product #1",
                            Price = 52.31045976854417,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #2",
                            Name = "Product #2",
                            Price = 134.13288418954838,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #3",
                            Name = "Product #3",
                            Price = 288.57385102779318,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #4",
                            Name = "Product #4",
                            Price = 32.107147961904829,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #5",
                            Name = "Product #5",
                            Price = 779.95758779065568,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #6",
                            Name = "Product #6",
                            Price = 33.741850157148136,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #7",
                            Name = "Product #7",
                            Price = 707.06673254587997,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #8",
                            Name = "Product #8",
                            Price = 77.92570708502349,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #9",
                            Name = "Product #9",
                            Price = 500.12135413480985,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #10",
                            Name = "Product #10",
                            Price = 489.81546770679557,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #11",
                            Name = "Product #11",
                            Price = 79.666317035754361,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #12",
                            Name = "Product #12",
                            Price = 934.49188045528331,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #13",
                            Name = "Product #13",
                            Price = 154.61785065085527,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #14",
                            Name = "Product #14",
                            Price = 82.796750278583147,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #15",
                            Name = "Product #15",
                            Price = 207.76785511372978,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #16",
                            Name = "Product #16",
                            Price = 81.154866048206983,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #17",
                            Name = "Product #17",
                            Price = 192.06622867475554,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #18",
                            Name = "Product #18",
                            Price = 145.12832783960195,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #19",
                            Name = "Product #19",
                            Price = 418.87005629896652,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #20",
                            Name = "Product #20",
                            Price = 532.60467138448951,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #21",
                            Name = "Product #21",
                            Price = 79.961964733880933,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #22",
                            Name = "Product #22",
                            Price = 120.94498580272543,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #23",
                            Name = "Product #23",
                            Price = 744.05855924126627,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #24",
                            Name = "Product #24",
                            Price = 125.81836507041864,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #25",
                            Name = "Product #25",
                            Price = 448.92609555689904,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #26",
                            Name = "Product #26",
                            Price = 177.24312174936904,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #27",
                            Name = "Product #27",
                            Price = 360.09464063453237,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #28",
                            Name = "Product #28",
                            Price = 59.539478668728599,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #29",
                            Name = "Product #29",
                            Price = 294.90683928500249,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #30",
                            Name = "Product #30",
                            Price = 155.2606864624008,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #31",
                            Name = "Product #31",
                            Price = 210.46839632022585,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #32",
                            Name = "Product #32",
                            Price = 202.93302202547576,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #33",
                            Name = "Product #33",
                            Price = 26.860235576918459,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #34",
                            Name = "Product #34",
                            Price = 357.44564731346708,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #35",
                            Name = "Product #35",
                            Price = 221.14216357383046,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #36",
                            Name = "Product #36",
                            Price = 122.03110268015,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #37",
                            Name = "Product #37",
                            Price = 111.42373533985752,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #38",
                            Name = "Product #38",
                            Price = 267.24109141865796,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #39",
                            Name = "Product #39",
                            Price = 432.44235089954094,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #40",
                            Name = "Product #40",
                            Price = 320.95426727875798,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #41",
                            Name = "Product #41",
                            Price = 1.9699412556225162,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #42",
                            Name = "Product #42",
                            Price = 410.89394459216572,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #43",
                            Name = "Product #43",
                            Price = 37.11332770302581,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #44",
                            Name = "Product #44",
                            Price = 180.79710310129315,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #45",
                            Name = "Product #45",
                            Price = 281.41500027636761,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #46",
                            Name = "Product #46",
                            Price = 413.69809761536214,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #47",
                            Name = "Product #47",
                            Price = 124.86475204576961,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #48",
                            Name = "Product #48",
                            Price = 260.40264800861604,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #49",
                            Name = "Product #49",
                            Price = 25.08946658255973,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #50",
                            Name = "Product #50",
                            Price = 30.423130761097713,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 51,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #51",
                            Name = "Product #51",
                            Price = 537.38406230387466,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 52,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #52",
                            Name = "Product #52",
                            Price = 626.4176101137034,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 53,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #53",
                            Name = "Product #53",
                            Price = 51.645723330623348,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 54,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #54",
                            Name = "Product #54",
                            Price = 69.639896494168738,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 55,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #55",
                            Name = "Product #55",
                            Price = 25.587433495366682,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 56,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #56",
                            Name = "Product #56",
                            Price = 419.6294949267197,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 57,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #57",
                            Name = "Product #57",
                            Price = 11.693403774729653,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 58,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #58",
                            Name = "Product #58",
                            Price = 855.8960652881749,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 59,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #59",
                            Name = "Product #59",
                            Price = 135.09805496134703,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 60,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #60",
                            Name = "Product #60",
                            Price = 186.29129857490366,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 61,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #61",
                            Name = "Product #61",
                            Price = 17.665726327181666,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 62,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #62",
                            Name = "Product #62",
                            Price = 20.596080674136097,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 63,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #63",
                            Name = "Product #63",
                            Price = 556.39885795647228,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 64,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #64",
                            Name = "Product #64",
                            Price = 646.30490008103891,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 65,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #65",
                            Name = "Product #65",
                            Price = 270.40230794223135,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 66,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #66",
                            Name = "Product #66",
                            Price = 504.32282781895384,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 67,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #67",
                            Name = "Product #67",
                            Price = 290.0254012225314,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 68,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #68",
                            Name = "Product #68",
                            Price = 121.92822031766559,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 69,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #69",
                            Name = "Product #69",
                            Price = 446.98579801385557,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 70,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #70",
                            Name = "Product #70",
                            Price = 458.40247740801544,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 71,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #71",
                            Name = "Product #71",
                            Price = 741.46677750789877,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 72,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #72",
                            Name = "Product #72",
                            Price = 522.50120110926275,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 73,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #73",
                            Name = "Product #73",
                            Price = 36.238745672739455,
                            Stock = 6,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 74,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #74",
                            Name = "Product #74",
                            Price = 25.113644327555619,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 75,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #75",
                            Name = "Product #75",
                            Price = 13.348695254581372,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 76,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #76",
                            Name = "Product #76",
                            Price = 233.35514603804572,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 77,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #77",
                            Name = "Product #77",
                            Price = 128.0444901455401,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 78,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #78",
                            Name = "Product #78",
                            Price = 18.247000979374629,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 79,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #79",
                            Name = "Product #79",
                            Price = 97.291592842569386,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 80,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #80",
                            Name = "Product #80",
                            Price = 210.13741056441208,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 81,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #81",
                            Name = "Product #81",
                            Price = 610.01264599431897,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 82,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #82",
                            Name = "Product #82",
                            Price = 34.578907962226729,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 83,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #83",
                            Name = "Product #83",
                            Price = 429.32941727960923,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 84,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #84",
                            Name = "Product #84",
                            Price = 440.64551864967007,
                            Stock = 5,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 85,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #85",
                            Name = "Product #85",
                            Price = 34.460516546136006,
                            Stock = 3,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 86,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #86",
                            Name = "Product #86",
                            Price = 454.18519778092633,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 87,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #87",
                            Name = "Product #87",
                            Price = 139.91334086373138,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 88,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #88",
                            Name = "Product #88",
                            Price = 396.66991489784317,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 89,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #89",
                            Name = "Product #89",
                            Price = 327.9548068232624,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 90,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #90",
                            Name = "Product #90",
                            Price = 623.96912414858548,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 91,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #91",
                            Name = "Product #91",
                            Price = 701.05762502600328,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 92,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #92",
                            Name = "Product #92",
                            Price = 368.60046606911368,
                            Stock = 1,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 93,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #93",
                            Name = "Product #93",
                            Price = 113.0488448166516,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 94,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #94",
                            Name = "Product #94",
                            Price = 269.99275828245692,
                            Stock = 9,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 95,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #95",
                            Name = "Product #95",
                            Price = 16.004112472759612,
                            Stock = 8,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 96,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #96",
                            Name = "Product #96",
                            Price = 317.89037571609504,
                            Stock = 7,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 97,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #97",
                            Name = "Product #97",
                            Price = 179.80706792036401,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 98,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #98",
                            Name = "Product #98",
                            Price = 688.28242574738454,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 99,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #99",
                            Name = "Product #99",
                            Price = 19.731082663746125,
                            Stock = 4,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 100,
                            CreatedBy = "unknown",
                            CreatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "Description for product #100",
                            Name = "Product #100",
                            Price = 5.858275482365058,
                            Stock = 2,
                            UpdatedBy = "unknown",
                            UpdatedOn = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
